export const FETCH_WIDGETS = 'FETCH_WIDGETS';
export const FETCH_WIDGETS_SUCCESS = 'FETCH_WIDGETS_SUCCESS';
export const FETCH_WIDGETS_FAILURE = 'FETCH_WIDGETS_FAILURE';
export const RESET_WIDGETS = 'RESET_WIDGETS';
